title: Fresh Crowd Blog
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4631327292881906
  brandStrength: 0.08260776218958199
  lightness: 0.4691378076095134
  brandColors:
    - '#000000'
    - '#0F76BD'
    - '#0B9444'
    - '#04421E'
    - '#0A5588'
  rhythmicContrast: 0.1737761946860701
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 'Fresh Crowd '
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.968335225712508
layout_spectrum: 0.67447
