name: FreshCrowd
favicon: null
layout_spectrum: 0.67447
typography_spectrum: 0.968335225712508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a77ba'
    - '#1a9347'
    - '#000000'
    - '#0000ff'
    - '#00ff00'
  brandStrength: 0.08260776218958199
  lightness: 0.4691378076095134
  saturation: 0.4631327292881906
  rhythmicContrast: 0.17377619468607008
purpose: []
